# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0005_auto_20171020_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
    ]
